### model
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct # This is the model being trained
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_alpha: 16
lora_target: all

### dataset
dataset: identity,alpaca_en_demo # Replace with your current task dataset(s)
template: llama3
cutoff_len: 2048
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/llama3-8b/lora/ssr_sft # Updated output directory for SSR
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# eval_dataset: alpaca_en_demo
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500

### Continual Learning Settings ###

# SSR Specific Arguments
use_ssr: true
base_model_path: meta-llama/Meta-Llama-3-8B-Instruct # Required for SSR: Path to the base model for ICL generation
num_shots: 2
n_clusters: 20
pseudo_sample_memory: 200 # Number of pseudo samples to keep per task
pseudo_samples_dir: pseudo_samples_ssr # Directory for storing SSR pseudo samples
previous_task_model: path/to/previous/task/model # Model from previous task, used for generating pseudo samples