model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
batch_size: 16
cl_tasks: amazon
template: llama3
save_dir: saves/cl_eval_results

# moelora evaluate option
eval_mode: single
use_moelora_eval: true
cl_tuning_type: lora
do_sample: false
num_beams: 1